server:
  port: 8762 # 端口
spring:
  application:
    name: eureka-server2 # 应用名称，会在Eureka中显示
eureka:
  instance:
    hostname: eureka2002.pers.young #
  client:
    service-url: #EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://eureka1:8761/eureka/,http://eureka3:8763/eureka/
    register-with-eureka: false
    fetch-registry: false
